/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 545.8231802384812
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 547.3659515825432
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.9370227701334
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 543.8470882479112
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 554.9115873362916
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 551.6404282696353
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 546.9601328649087
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 543.2631734282002
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 556.9192939889281
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 545.0068438842131
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 557.8079081341386
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.3773489363729
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 555.827033106583
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 552.7098822843695
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 547.2101249139748
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 547.438717947231
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 554.358144223942
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 556.8464727782582
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 546.7302791923179
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 559.8870394132776
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 547.9898615201301
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 547.6855367603392
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 547.136051628637
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 542.9639606471885
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.7132036401749
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 543.2961280032908
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 542.9833643011707
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 542.6803971620062
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 548.8171145811331
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.2626395113549
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 543.3339949632266
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 547.2516794767987
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 542.9998686187165
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 557.087647460131
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.5607901578466
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.5588661598431
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.8010909338237
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 546.041377821988
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 543.78494129007
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 545.7955232131601
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 546.4051060372402
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.601805766181
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 544.280045272006
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.986998082295
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 547.0647717900397
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 543.7771958397632
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 544.9366294413196
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.3383629886832
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.1483608131634
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 542.2420778426806
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.8283762266494
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 542.9502205763442
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 542.5669938832266
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.616607544719
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.1840157636436
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 545.3827593171505
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 544.1691991768814
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 546.113065161542
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.2444643851968
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 549.832248881648
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 547.3572822460233
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 542.2721297874924
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.7368932563127
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 542.6991203749386
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 543.3345217701548
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 542.6653294906462
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 543.9006788652032
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 546.5622020879157
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 545.6153277249717
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 543.653522311633
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 545.65268280694
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.8400010370547
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 550.8888667692534
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 544.178964440687
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 550.8449647292374
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 553.5913419271378
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.6169668814804
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.0961320865823
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 546.9779211597884
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 547.6577279367116
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 544.6818977470512
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 544.4465134630535
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 553.604187535919
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 552.3721443174106
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.0655947659557
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.1878983718927
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.7701476015952
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.5989970691705
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 545.6725597580429
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.6307048086309
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.3486349788989
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.4675995820241
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 543.141918194077
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 549.4004780072181
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 543.593927788372
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.5731731663625
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.224357478056
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 542.5370732229459
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.6102498516141
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.0626715576574
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 542.5173186506947
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.9213467680916
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 543.9717345336676
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 544.7633549512236
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.7508580199091
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 542.5023725184733
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 542.660459931007
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 544.0142330259257
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.070620299971
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.7240725653968
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.7025316830668
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.8140813167757
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.0176646008142
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.6873833069269
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.1296200143988
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.3908390184241
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.5606234269975
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.591521963846
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 544.6225133184521
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.8319075342548
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.025641132691
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.168458889659
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.8056700279033
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 545.0619891016145
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.7912647313007
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.5977234233345
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.9199323680294
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 542.5123700937299
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 546.1936581539647
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.5256488785208
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 544.9388021373854
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 543.6076062785658
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.6523480780265
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.5240667259293
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 545.4394251436752
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.0014786073864
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.3812987052102
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.0690096534985
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 542.4571502679886
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 545.3145267947802
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 546.5468659262979
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.127553176932
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.8660464872851
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 542.3696550309576
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.9509750019772
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 545.008685189138
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 544.1648349303437
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 542.5743985156885
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.7065996826664
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.4387088726269
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 543.6819935666945
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.0017021753797
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 543.325719355482
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.558950283801
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.7810861251584
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.1958655986002
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.055720663174
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.1032223527305
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.2702558993246
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.9585633219559
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.5426287995065
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.4162867417335
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.6889531933695
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.4222833464252
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.171667116223
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.7195902568337
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 543.1701631199277
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.7504421997801
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.438484179317
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.9631641278835
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.1905246233036
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.6904354464793
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.5649100693481
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.0185798339619
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.1575680749171
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.1887482236486
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.0658539596348
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.3598971958749
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.5390777790872
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.7630452084779
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 542.353225561134
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.2755678685243
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.9096877323204
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.4029031727678
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.4925677887129
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.2962970432092
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 540.0059207762241
  warnings.warn(fmt.format(name, value), RuntimeWarning)
/home/hansdorfer/.local/lib/python3.8/site-packages/MulensModel/modelparameters.py:1224: RuntimeWarning: Strange value of angle xi_argument_of_latitude_reference: 541.2458430751076
  warnings.warn(fmt.format(name, value), RuntimeWarning)
The chain is shorter than 50 times the integrated autocorrelation time for 11 parameter(s). Use this estimate with caution and run a longer chain!
N/50 = 750;
tau: [3548.58389482 3739.54114744 4012.87323564 3655.49276082 3444.41640095
 3310.65770681 4020.80877939 3004.85978356 3314.12955723 3148.36482939
 3577.5912261 ]
