Traceback (most recent call last):
  File "ulens_model_fit.py", line 3260, in <module>
    with open(input_file, 'r') as data:
FileNotFoundError: [Errno 2] No such file or directory: 'sim27_12/PARAXALL/PAR-34-noaver.dat.7-.yaml'
