WARNING: leap-second auto-update failed due to the following exception: RuntimeError('Cache is locked after 5.00 s. This may indicate an astropy bug or that kill -9 was used. If you want to unlock the cache remove the directory /home/data/bl407/jwiniarczyk/.astropy/cache/download/py3/lock. Lock claims to be held by process 6608.',) [astropy.time.core]
The chain is shorter than 50 times the integrated autocorrelation time for 10 parameter(s). Use this estimate with caution and run a longer chain!
N/50 = 6;
tau: [32.72817136 33.70864501 34.24363138 31.91722922 31.70587408 31.18181452
 30.7604886  36.71715106 31.97270423 32.27195848]
WARNING:root:Too few points to create valid contours
WARNING:root:Too few points to create valid contours
